use_frameworks!
platform :ios, '10.0'

target 'RBSRealmBrowser_Example' do
  pod 'RBSRealmBrowser', :path => '../'
  pod 'SwiftLint'

end

target 'RBSRealmBrowser_Tests' do
    pod 'RBSRealmBrowser', :path => '../'
end

