source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'

target 'RBSRealmBrowser_Example', :exclusive => true do
  pod 'RBSRealmBrowser', :path => '../'
end

target 'RBSRealmBrowser_Tests', :exclusive => true do
  pod 'RBSRealmBrowser', :path => '../'

  
end
